
## Analysis of violation counts


```{r, results='hide', echo=FALSE, warning=FALSE, message=FALSE}
if (basename(getwd()) != "ChicagoVacantBuildingData") {setwd("..")}
##------------------------------------------------------------------------------
## INITIALIZATION
##------------------------------------------------------------------------------
rm(list=ls())
gc()
library(geneorama)
detach_nonstandard_packages()
library(geneorama)
loadinstall_libraries(c("geneorama", "data.table", "ggplot2", "knitr",
						"reshape2", "corrplot", "rpart", "party"))
sourceDir("functions/")
op <- readRDS("data/op.Rds")  ## Default par
par(op)

##------------------------------------------------------------------------------
## LOAD DATA OBJECTS
##------------------------------------------------------------------------------

## Filepaths to data objects used in this script
## See associated R files for documentation
fp1 <- 'data/op'
fp2 <- "data/Vacant_and_Abandoned_Buildings_-_Violations"
fp3 <- "data/Building_Violations"
# fp4 <- "data/Building_Violations__VIOLATION_ORDINANCE"
# fp5 <- "data/Building_Violations__VIOLATION_ORDINANCE_dummy_matrix"

## Create Rds files, if they don't exist locally
if(!file.exists(paste0(fp1, ".Rds"))) source(paste0(fp1, ".R"), local=TRUE, echo=TRUE)
if(!file.exists(paste0(fp2, ".Rds"))) source(paste0(fp2, ".R"), local=TRUE, echo=TRUE)
if(!file.exists(paste0(fp3, ".Rds"))) source(paste0(fp3, ".R"), local=TRUE, echo=TRUE)
# if(!file.exists(paste0(fp4, ".Rds"))) source(paste0(fp4, ".R"), local=TRUE, echo=TRUE)
# if(!file.exists(paste0(fp5, ".Rds"))) source(paste0(fp5, ".R"), local=TRUE, echo=TRUE)

## LOAD RDS FILES
op <- readRDS(paste0(fp1, ".Rds"))
datVacant <- readRDS(paste0(fp2, ".Rds"))
datBuild <- readRDS(paste0(fp3, ".Rds"))
# VIOLATION_ORDINANCE <- readRDS(paste0(fp4, ".Rds"))
# VIOLATION_ORDINANCE_dmat <- readRDS(paste0(fp5, ".Rds"))

##------------------------------------------------------------------------------
## MODIFY DATA
##------------------------------------------------------------------------------

## CONVERT NAMES
setnames(datBuild, 
		 old = colnames(datBuild), 
		 new = gsub("\\.", "_", colnames(datBuild)))
setnames(datVacant, 
		 old = colnames(datVacant), 
		 new = gsub("\\.", "_", colnames(datVacant)))

## CONVERT APPROPRIATE COLUMNS TO FACTOR
names_factors_vacant <- c("Issuing_Department", "Violation_Type", 
						  "Disposition_Description", "Entity_or_Person_s_")
convert_datatable_StringFactor(dat = datVacant, cols = names_factors_vacant)

## CONVERT APPROPRIATE COLUMNS TO FACTOR
names_factors_build <- c("VIOLATION_STATUS", "VIOLATION_CODE", 
						 "VIOLATION_DESCRIPTION", "VIOLATION_ORDINANCE", 
						 "INSPECTOR_ID", "INSPECTION_STATUS", 
						 "INSPECTION_WAIVED", "INSPECTION_CATEGORY", 
						 "DEPARTMENT_BUREAU")
convert_datatable_StringFactor(dat = datBuild, cols = names_factors_build)

## Convert column classes to interger based dates
convert_datatable_DateIDate(datBuild)
convert_datatable_DateIDate(datVacant)

## CONVERT LATITUDE TO NUMERIC
datBuild[ , LATITUDE:=as.numeric(LATITUDE)]

## ADD FIELD: id
datBuild[ , id := 1:nrow(datBuild)]
# names(VIOLATION_ORDINANCE) = 1:length(VIOLATION_ORDINANCE)
```


```{r, results='hide', echo=FALSE, warning=FALSE}
##------------------------------------------------------------------------------
## BASIC DATA SUMMARIES
##------------------------------------------------------------------------------

## Basic data summaries
str(datVacant)
str(datBuild)

## Show NA and Unique Value (and remove columns with only one unique value)
naVacant <- NAsummary(datVacant)
naBuild <- NAsummary(datBuild)
naVacant
naBuild

## ONLY KEEP FIELDS WITH MORE THAN ONE UNIQUE VALUE
datVacant <- datVacant[ , which(naVacant$nUnique > 1), with = F]
datBuild <- datBuild[ , which(naBuild$nUnique > 1), with = F]

## Remove NA summaries
rm(naVacant, naBuild)
```


```{r}
opts_chunk$set(tidy=FALSE, fig.width=12, results="hold")
```


## Violation counts are declining

```{r}
## Group the data by month
Violations_grpbyDate <- datBuild[
	i = TRUE,
	j = list(.N),
	by = list(yearmo=round(VIOLATION_DATE, "month"))]
ggplot(data = Violations_grpbyDate) + 
	aes(yearmo, y = N) +
	geom_line()
```

## Violation counts after grouping by address

```{r}
## Group violations by address and day
Violations_grpbyAddress <- datBuild[
	i= TRUE,
	j = list(.N), 
	by = list(VIOLATION_DATE, ADDRESS)]
## Group the grouped data by month
Violations_grpbyAddress_byDate <- Violations_grpbyAddress[
	i = TRUE,
	j = .N, 
	by = list(yearmo=round(VIOLATION_DATE, "month"))]
## Plot the results
ggplot(data = Violations_grpbyAddress_byDate) + 
	aes(yearmo, y = N) +
	geom_line()
```

## Vacant Building counts 

Vacant Building counts increased over the same time, and they're missing from the violation data

```{r}
VacantProperties_grpbyAddress <- datVacant[
	i = TRUE,
	j = list(.N), 
	by = list(Issued_Date, Property_Address)]
VacantProperties_grpbyAddress_byDate <- VacantProperties_grpbyAddress[
	i = TRUE,
	j = .N, 
	by = list(yearmo=round(Issued_Date, "month"))]
ggplot(data = VacantProperties_grpbyAddress_byDate[-1]) + 
	aes(yearmo, y = N) +
	xlim(range(Violations_grpbyAddress_byDate$yearmo)) +
	geom_line()

```












